version: '3.8'

services:
  mariadb:
    image: mariadb:11
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: clotfilmsdb
      MYSQL_USER: clotuser
      MYSQL_PASSWORD: clotpass
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db

  clotfilms-app:
    build: .
    container_name: clotfilms-app
    restart: always
    depends_on:
      - mariadb
      - mongodb
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mariadb:3306/clotfilmsdb
      SPRING_DATASOURCE_USERNAME: clotuser
      SPRING_DATASOURCE_PASSWORD: clotpass
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/clotfilms

volumes:
  mariadb_data:
  mongodb_data:
